//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FOOD()
        {
            this.RECIPEs = new HashSet<RECIPE>();
        }
    
        public string Food_ID { get; set; }
        public string Menu_ID { get; set; }
        public string Type { get; set; }
        public string IsGlutenFree { get; set; }
        public string IsVegeterian { get; set; }
        public string IsSpicy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECIPE> RECIPEs { get; set; }
        public virtual MENU MENU { get; set; }
    }
}
