//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class MEMBER
    {
        [DataMember]
        public string Member_ID { get; set; }
        [DataMember]
        public string Person_ID { get; set; }
        [DataMember]
        public Nullable<int> Reward_Points { get; set; }
    
        public virtual PERSON PERSON { get; set; }
    }
}
