//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PizzaStoreEntities : DbContext
    {
        public PizzaStoreEntities()
            : base("name=PizzaStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<CHEF> CHEFs { get; set; }
        public virtual DbSet<DELIVERY_ADDRESS> DELIVERY_ADDRESS { get; set; }
        public virtual DbSet<DRINK> DRINKs { get; set; }
        public virtual DbSet<DRIVER> DRIVERs { get; set; }
        public virtual DbSet<DRIVER_AUDIT> DRIVER_AUDIT { get; set; }
        public virtual DbSet<FOOD> FOODs { get; set; }
        public virtual DbSet<INGREDIENT> INGREDIENTs { get; set; }
        public virtual DbSet<MEMBER> MEMBERs { get; set; }
        public virtual DbSet<MENU> MENUs { get; set; }
        public virtual DbSet<OFFER> OFFERs { get; set; }
        public virtual DbSet<OFFER_ITEM> OFFER_ITEM { get; set; }
        public virtual DbSet<ORDER> ORDERs { get; set; }
        public virtual DbSet<ORDER_ITEM> ORDER_ITEM { get; set; }
        public virtual DbSet<PERSON> People { get; set; }
        public virtual DbSet<RECIPE> RECIPEs { get; set; }
        public virtual DbSet<STOCK> STOCKs { get; set; }
        public virtual DbSet<TEMP_DELIVERYADDRESS> TEMP_DELIVERYADDRESS { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
    }
}
