//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER()
        {
            this.ORDER_ITEM = new HashSet<ORDER_ITEM>();
        }

        [DataMember]
        public string Order_ID { get; set; }
        [DataMember]
        public string Member_ID { get; set; }
        [DataMember]
        public string Driver_ID { get; set; }
        [DataMember]
        public Nullable<decimal> Total_Price { get; set; }
        [DataMember]
        public string DELIVERYADDRESSID { get; set; }
        [DataMember]
        public string TEMP_DELIVERYADDRESSID { get; set; }
        [DataMember]
        public string ISPAID { get; set; }
        [DataMember]
        public System.DateTime Date { get; set; }
        [DataMember]
        public string Time { get; set; }
        [DataMember]
        public string IsDelivery { get; set; }
        [DataMember]
        public string Status { get; set; }
    
        public virtual DELIVERY_ADDRESS DELIVERY_ADDRESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_ITEM> ORDER_ITEM { get; set; }
        public virtual TEMP_DELIVERYADDRESS TEMP_DELIVERYADDRESS { get; set; }
    }
}
