//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class ORDER_ITEM
    {
        [DataMember]
        public string Order_Item_ID { get; set; }
        [DataMember]
        public string Order_ID { get; set; }
        [DataMember]
        public string Menu_ID { get; set; }
        [DataMember]
        public short Quantity { get; set; }
        [DataMember]
        public string Notes { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual ORDER ORDER { get; set; }
    }
}
