//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class PERSON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSON()
        {
            this.UserLogins = new HashSet<UserLogin>();
        }
    
        [DataMember]
        public string Person_ID { get; set; }
        [DataMember]
        public string Forename { get; set; }
        [DataMember]
        public string Surname { get; set; }
        [DataMember]
        public System.DateTime DOB { get; set; }
        [DataMember]
        public string Email { get; set; }
        [DataMember]
        public string Mobile_Number { get; set; }
        [DataMember]
        public string Town_City { get; set; }
        [DataMember]
        public string County { get; set; }
        [DataMember]
        public string Postcode { get; set; }
        [DataMember]
        public string Address2 { get; set; }
        [DataMember]
        public string Address1 { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        public virtual CHEF CHEF { get; set; }
        public virtual DRIVER DRIVER { get; set; }
        public virtual MEMBER MEMBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLogin> UserLogins { get; set; }
    }
}
