//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIPE
    {
        public string Ingredient_ID { get; set; }
        public string Food_ID { get; set; }
        public string ID { get; set; }
    
        public virtual FOOD FOOD { get; set; }
        public virtual INGREDIENT INGREDIENT { get; set; }
    }
}
