//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK
    {
        public string Stock_ID { get; set; }
        public string Stock_Name { get; set; }
        public Nullable<short> Quantity { get; set; }
        public Nullable<decimal> Cost { get; set; }
    }
}
